"""init schema

Revision ID: 662fd9ca29c0
Revises: 
Create Date: 2026-02-04 22:16:02.371005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '662fd9ca29c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_products_category_id'), table_name='products')
    op.drop_index(op.f('idx_products_name'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('idx_payments_wid'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('idx_user_purchases_uid'), table_name='user_purchases')
    op.drop_table('user_purchases')
    op.drop_index(op.f('idx_wallets_uid'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('idx_product_inventories_data'), table_name='product_inventories')
    op.drop_index(op.f('idx_product_inventories_pid'), table_name='product_inventories')
    op.drop_index(op.f('idx_product_inventories_status'), table_name='product_inventories')
    op.drop_table('product_inventories')
    op.drop_index(op.f('idx_product_category_keyword'), table_name='product_categories')
    op.drop_table('product_categories')
    op.drop_index(op.f('idx_email'), table_name='users')
    op.drop_index(op.f('idx_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), server_default=sa.text("'anonymous'::character varying"), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), server_default=sa.text("'member'::character varying"), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("role::text = ANY (ARRAY['admin'::character varying, 'member'::character varying]::text[])", name=op.f('users_role_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('users_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('idx_email'), 'users', ['email'], unique=False)
    op.create_table('product_categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('keyword', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('product_categories_pkey'))
    )
    op.create_index(op.f('idx_product_category_keyword'), 'product_categories', ['keyword'], unique=False)
    op.create_table('product_inventories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'available'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['available'::character varying, 'sold'::character varying, 'locked'::character varying, 'refuned'::character varying]::text[])", name=op.f('product_inventories_status_check')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_inventories_pid')),
    sa.PrimaryKeyConstraint('id', name=op.f('product_inventories_pkey')),
    sa.UniqueConstraint('product_id', 'data', name=op.f('uk_product_pid'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_product_inventories_status'), 'product_inventories', ['status'], unique=False)
    op.create_index(op.f('idx_product_inventories_pid'), 'product_inventories', ['product_id'], unique=False)
    op.create_index(op.f('idx_product_inventories_data'), 'product_inventories', ['data'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=18, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('balance >= 0::numeric', name=op.f('wallets_balance_check')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('wallets_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('wallets_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('wallets_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_wallets_uid'), 'wallets', ['user_id'], unique=False)
    op.create_table('user_purchases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('total_price', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('quantity > 0', name=op.f('user_purchaes_quantity_check')),
    sa.CheckConstraint('total_price > 0::numeric', name=op.f('user_purchaes_total_price_check')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_purchaes_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_purchaes_pkey'))
    )
    op.create_index(op.f('idx_user_purchases_uid'), 'user_purchases', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('wallet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['pending'::character varying, 'success'::character varying, 'failed'::character varying]::text[])", name=op.f('payments_status_check')),
    sa.CheckConstraint('amount > 0::numeric', name=op.f('payments_amount_check')),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name=op.f('payments_wallet_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('payments_pkey'))
    )
    op.create_index(op.f('idx_payments_wid'), 'payments', ['wallet_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('stock', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('sold', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('discount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('subtitle', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), server_default=sa.text("'no description'::text"), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=50), server_default=sa.text("'random'::character varying"), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('icons', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('discount >= 0', name=op.f('products_discount_check')),
    sa.CheckConstraint('price > 0::numeric', name=op.f('products_price_check')),
    sa.CheckConstraint('sold >= 0', name=op.f('products_sold_check')),
    sa.CheckConstraint('stock >= 0', name=op.f('products_stock_check')),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], name=op.f('fk_products_cid')),
    sa.PrimaryKeyConstraint('id', name=op.f('products_pkey')),
    sa.UniqueConstraint('category_id', 'name', name=op.f('uk_products_cid_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('idx_products_category_id'), 'products', ['category_id'], unique=False)
    # ### end Alembic commands ###
